# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/code/RISCV/RISCV/RISCV.srcs/sources_1/ip/dram/dram.xci
# IP: The module: 'dram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/RISCV/RISCV/RISCV.srcs/sources_1/ip/dram/dram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/code/RISCV/RISCV/RISCV.srcs/sources_1/ip/dram/dram.xci
# IP: The module: 'dram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/code/RISCV/RISCV/RISCV.srcs/sources_1/ip/dram/dram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
